In [3]:
#Import all of the relevant libraries
import pandas as pd
from pyomo.environ import *
from pyomo.opt import SolverFactory

In [6]:
!git clone https://github.com/dhom-wisc/Data-Sets-Information.git

fatal: destination path 'Data-Sets-Information' already exists and is not an empty directory.

In [5]:
#reading in distance data
distdata = pd.read_excel(open('P3_DCLocation.xlsx','rb'), sheet_name='distcost') #Change to your file name and sheet name
distdata.head()

,Unnamed: 0,New York,Los Angeles,Chicago,Houston,Phoenix,Philadelphia,San Antonio,San Diego,Dallas,...,Anchorage,Greensboro,Plano,Newark,Lincoln,Orlando,Irvine,Toledo,Jersey City,Chula Vista
0,Durham,2693,1752,1820,2585,2861,3446,3814,3100,2098,...,2240,2169,2906,1592,3903,1351,3545,2851,1936,3710
1,Fort Wayne,2690,2581,1851,2175,1851,1895,2529,2525,1872,...,1042,2098,2770,1614,835,2652,694,294,1702,1341
2,St. Petersburg,2480,3128,2782,2213,2837,3252,2588,2735,1111,...,1521,2142,2392,500,1800,1270,1132,597,1730,3385
3,Laredo,5144,5693,3046,5593,4414,4492,5348,5757,4681,...,5324,5901,4510,3718,3165,5423,3204,3431,5895,4124
4,Buffalo,3436,4475,4340,5177,4286,4186,4459,4863,5337,...,5642,5111,5504,4217,4031,4532,5300,5761,4460,4240

In [4]:
#converting distance data to a list of lists
distances = distdata.loc[:, 'New York':'Chula Vista'].values.tolist()
distances

[[2693,
  1752,
  1820,
  2585,
  2861,
  3446,
  3814,
  3100,
  2098,
  2113,
  3576,
  2312,
  3298,
  2423,
  3268,
  1754,
  1433,
  2504,
  2132,
  1368,
  3656,
  3182,
  2368,
  3817,
  1970,
  2430,
  1896,
  2058,
  2076,
  3375,
  2721,
  1831,
  3345,
  1245,
  1920,
  3707,
  1249,
  2722,
  3883,
  1670,
  1036,
  2156,
  2447,
  3725,
  2589,
  3766,
  2144,
  2100,
  980,
  2584,
  1690,
  3946,
  3390,
  2062,
  3830,
  3705,
  2660,
  2099,
  1897,
  1008,
  3041,
  1284,
  1903,
  1716,
  2956,
  3253,
  2240,
  2169,
  2906,
  1592,
  3903,
  1351,
  3545,
  2851,
  1936,
  3710],
 [2690,
  2581,
  1851,
  2175,
  1851,
  1895,
  2529,
  2525,
  1872,
  2910,
  2469,
  1590,
  2463,
  1272,
  1596,
  2596,
  1544,
  2682,
  1271,
  2412,
  1408,
  1154,
  649,
  1246,
  1815,
  2392,
  3167,
  2191,
  1977,
  1317,
  2151,
  280,
  1561,
  1749,
  1776,
  3064,
  1004,
  1710,
  1150,
  2697,
  998,
  2474,
  454,
  1641,
  1433,
  553,
  2226,
  2290,
  433,
  1461,
  2440,
  2914,
  1262,
  1739,
  1853,
  1804,
  620,
  2568,
  2115,
  2531,
  2719,
  2165,
  2496,
  1130,
  2392,
  440,
  1042,
  2098,
  2770,
  1614,
  835,
  2652,
  694,
  294,
  1702,
  1341],
 [2480,
  3128,
  2782,
  2213,
  2837,
  3252,
  2588,
  2735,
  1111,
  2135,
  3056,
  851,
  970,
  1186,
  3376,
  1720,
  1501,
  2281,
  3185,
  1694,
  3380,
  1450,
  540,
  764,
  1966,
  3232,
  1937,
  2442,
  1223,
  1858,
  3261,
  2936,
  2887,
  1422,
  1380,
  2915,
  2784,
  1776,
  610,
  2755,
  2820,
  1207,
  778,
  2683,
  528,
  905,
  2511,
  806,
  906,
  1393,
  445,
  3266,
  3076,
  1519,
  770,
  2006,
  3396,
  1332,
  820,
  2843,
  2052,
  2392,
  1697,
  2508,
  2957,
  1509,
  1521,
  2142,
  2392,
  500,
  1800,
  1270,
  1132,
  597,
  1730,
  3385],
 [5144,
  5693,
  3046,
  5593,
  4414,
  4492,
  5348,
  5757,
  4681,
  4533,
  4405,
  5333,
  4306,
  3403,
  3782,
  3754,
  3524,
  3855,
  3580,
  3829,
  4078,
  4486,
  2988,
  3220,
  5778,
  4620,
  2981,
  4807,
  5638,
  4776,
  5497,
  4108,
  5196,
  5278,
  5710,
  4113,
  5842,
  4642,
  4776,
  5026,
  4474,
  4349,
  3672,
  5757,
  5649,
  4273,
  5370,
  3850,
  3794,
  4153,
  4995,
  4032,
  4030,
  5172,
  3209,
  4121,
  5232,
  4663,
  4116,
  3117,
  4508,
  5142,
  3643,
  3896,
  3429,
  4216,
  5324,
  5901,
  4510,
  3718,
  3165,
  5423,
  3204,
  3431,
  5895,
  4124],
 [3436,
  4475,
  4340,
  5177,
  4286,
  4186,
  4459,
  4863,
  5337,
  5477,
  4339,
  4425,
  3948,
  5418,
  4571,
  5648,
  5010,
  4546,
  5827,
  3108,
  4478,
  4235,
  5418,
  5752,
  5130,
  5370,
  5575,
  2897,
  4832,
  4594,
  4915,
  3281,
  3891,
  3471,
  5114,
  4808,
  5397,
  3945,
  4379,
  5802,
  3495,
  3047,
  4002,
  5466,
  4204,
  5602,
  4088,
  4963,
  5467,
  5407,
  4688,
  5050,
  3543,
  3287,
  5026,
  3169,
  5226,
  3764,
  5289,
  3945,
  4291,
  3499,
  3859,
  5404,
  3706,
  4022,
  5642,
  5111,
  5504,
  4217,
  4031,
  4532,
  5300,
  5761,
  4460,
  4240],
 [3587,
  1973,
  2033,
  3632,
  935,
  1516,
  3159,
  3690,
  1811,
  2076,
  816,
  3262,
  3575,
  1055,
  2556,
  2467,
  1030,
  2372,
  1718,
  3731,
  2793,
  1426,
  2015,
  799,
  2400,
  1541,
  967,
  3366,
  2152,
  919,
  3076,
  3757,
  2924,
  2992,
  2295,
  2555,
  1134,
  2691,
  1960,
  3023,
  3265,
  2358,
  3576,
  2376,
  851,
  3153,
  3541,
  1931,
  3528,
  1872,
  1660,
  2482,
  847,
  2420,
  2703,
  1185,
  3435,
  860,
  3331,
  1035,
  1300,
  879,
  1211,
  969,
  2825,
  2011,
  3327,
  1242,
  2413,
  2880,
  2368,
  902,
  3515,
  2353,
  3686,
  1423],
 [2404,
  794,
  2885,
  998,
  2791,
  1674,
  1414,
  133,
  2143,
  897,
  2074,
  2074,
  2424,
  1281,
  760,
  162,
  1034,
  587,
  1963,
  454,
  866,
  2421,
  2887,
  1375,
  556,
  2246,
  1156,
  318,
  2743,
  654,
  1976,
  582,
  193,
  2431,
  767,
  229,
  1531,
  509,
  680,
  112,
  1037,
  20,
  2910,
  1544,
  1237,
  449,
  1696,
  1888,
  595,
  403,
  2640,
  386,
  1053,
  375,
  961,
  2286,
  3015,
  1756,
  25,
  2058,
  388,
  2668,
  2833,
  2611,
  2334,
  71,
  47,
  486,
  2743,
  1955,
  1302,
  500,
  1397,
  1173,
  1758,
  1622],
 [2805,
  2738,
  2750,
  3852,
  2442,
  3986,
  2293,
  2814,
  4996,
  3190,
  3866,
  2347,
  4851,
  2507,
  4593,
  4050,
  4426,
  3019,
  5119,
  2437,
  2603,
  3375,
  4346,
  2416,
  2781,
  2352,
  3357,
  5152,
  4450,
  3544,
  2658,
  4767,
  2960,
  4607,
  4704,
  3259,
  2853,
  4841,
  4659,
  4545,
  3049,
  4514,
  3678,
  5010,
  3968,
  2591,
  3026,
  2247,
  5133,
  3278,
  2789,
  2921,
  4237,
  3058,
  4708,
  2429,
  4269,
  3260,
  4857,
  3374,
  4559,
  3890,
  2357,
  5169,
  4112,
  2832,
  3935,
  4184,
  4501,
  2995,
  3109,
  2585,
  5113,
  4117,
  2191,
  3099],
 [5486,
  5742,
  3576,
  4881,
  5403,
  3433,
  4993,
  5424,
  4196,
  5447,
  5800,
  5171,
  4685,
  3929,
  4077,
  5420,
  4070,
  3112,
  3724,
  5879,
  4852,
  4192,
  3546,
  5235,
  5149,
  4263,
  3622,
  5174,
  3466,
  4843,
  4729,
  4242,
  5962,
  5991,
  5831,
  3066,
  4832,
  5892,
  5423,
  3520,
  3742,
  5724,
  3689,
  5847,
  4678,
  5722,
  5791,
  4543,
  5504,
  4336,
  5645,
  3695,
  4088,
  5956,
  5817,
  4791,
  3777,
  4766,
  4574,
  4078,
  5547,
  4144,
  4826,
  3098,
  4192,
  4816,
  3477,
  3824,
  5751,
  5908,
  5520,
  5247,
  3234,
  3079,
  3536,
  3174],
 [1940,
  3552,
  3835,
  2819,
  3095,
  3953,
  2891,
  3931,
  3382,
  2423,
  3349,
  3216,
  3785,
  3779,
  3441,
  3287,
  3359,
  2383,
  4435,
  3771,
  2235,
  2633,
  3804,
  4758,
  1883,
  2016,
  3704,
  3740,
  2786,
  3323,
  3982,
  2591,
  2406,
  2449,
  4716,
  2906,
  3285,
  4724,
  3627,
  3229,
  2034,
  4110,
  3061,
  3373,
  4720,
  3179,
  1978,
  2972,
  2263,
  2184,
  4356,
  3452,
  3428,
  3837,
  3900,
  1882,
  3528,
  2721,
  2870,
  2549,
  1950,
  4754,
  3080,
  3625,
  4374,
  4557,
  3509,
  4581,
  3216,
  3402,
  2129,
  2490,
  2408,
  3922,
  3355,
  2751],
 [2761,
  1172,
  2523,
  1969,
  283,
  2261,
  1038,
  325,
  1535,
  1336,
  1769,
  1535,
  444,
  2105,
  711,
  214,
  1646,
  2234,
  466,
  996,
  2210,
  1473,
  818,
  1431,
  2859,
  2966,
  711,
  1450,
  2129,
  2108,
  2896,
  1010,
  3085,
  902,
  1360,
  2922,
  2812,
  2572,
  922,
  243,
  1794,
  1263,
  2728,
  1475,
  1960,
  2664,
  263,
  1727,
  1567,
  3163,
  2162,
  2035,
  832,
  954,
  2841,
  828,
  649,
  2170,
  869,
  2342,
  1856,
  2410,
  443,
  550,
  3085,
  2829,
  1090,
  2643,
  1653,
  2105,
  2276,
  471,
  1503,
  2600,
  1282,
  1086],
 [3833,
  3329,
  2370,
  2616,
  3755,
  5022,
  4321,
  2348,
  2428,
  5016,
  3699,
  4305,
  4967,
  5047,
  3869,
  3057,
  3876,
  2346,
  2555,
  4872,
  4922,
  2808,
  3651,
  2677,
  4785,
  4041,
  2539,
  3645,
  2864,
  4741,
  4522,
  2734,
  3221,
  4810,
  3087,
  2412,
  2719,
  4438,
  3782,
  4899,
  3992,
  2872,
  4349,
  2699,
  2437,
  2691,
  2810,
  4963,
  3873,
  2531,
  3666,
  3351,
  4740,
  5266,
  3760,
  3217,
  4745,
  3790,
  3015,
  2330,
  2372,
  4854,
  3988,
  3643,
  3031,
  2434,
  3951,
  4730,
  2600,
  5305,
  3082,
  2965,
  4454,
  5100,
  3361,
  2396],
 [2434,
  2571,
  578,
  1138,
  1255,
  2683,
  2238,
  1294,
  187,
  2159,
  2015,
  1507,
  258,
  911,
  2204,
  943,
  1226,
  2487,
  2791,
  1102,
  817,
  619,
  254,
  981,
  612,
  2341,
  830,
  405,
  1483,
  536,
  2004,
  1948,
  1363,
  1361,
  48,
  2490,
  2000,
  215,
  1261,
  246,
  2826,
  2246,
  1369,
  751,
  2069,
  545,
  471,
  1748,
  2685,
  2445,
  280,
  1478,
  1744,
  1654,
  2607,
  612,
  1573,
  2021,
  1487,
  1594,
  769,
  955,
  1305,
  984,
  1558,
  541,
  2486,
  2415,
  2173,
  567,
  2612,
  2098,
  1876,
  160,
  1583,
  906],
 [2317,
  2960,
  1008,
  2292,
  1433,
  3614,
  2025,
  3456,
  3035,
  3709,
  2821,
  2748,
  2666,
  3412,
  1975,
  1027,
  3774,
  2002,
  3850,
  1832,
  2065,
  3125,
  1236,
  2898,
  1985,
  2395,
  1792,
  1293,
  1314,
  2501,
  1227,
  2809,
  3427,
  2784,
  2677,
  3721,
  1989,
  2541,
  2571,
  981,
  1975,
  1899,
  3317,
  1858,
  1740,
  2548,
  1466,
  2796,
  3606,
  1571,
  1124,
  2154,
  3647,
  2884,
  3156,
  2946,
  3050,
  1510,
  3119,
  1361,
  2099,
  3426,
  1022,
  3810,
  1782,
  3376,
  3033,
  2651,
  3318,
  1882,
  3572,
  3724,
  1241,
  2016,
  3966,
  3497],
 [4118,
  2281,
  2251,
  4915,
  5245,
  4029,
  5010,
  3365,
  4631,
  4156,
  3161,
  5049,
  3809,
  4254,
  5009,
  2497,
  4308,
  3455,
  5077,
  3861,
  4875,
  2566,
  4796,
  5006,
  4546,
  2939,
  4049,
  2629,
  2519,
  3487,
  5111,
  3265,
  5062,
  3915,
  3434,
  2445,
  2791,
  3944,
  2460,
  2716,
  3577,
  4589,
  2788,
  4636,
  3454,
  2908,
  4041,
  3712,
  4039,
  3139,
  2267,
  4695,
  4834,
  3984,
  4648,
  3464,
  4048,
  3673,
  2355,
  2872,
  2445,
  3246,
  4902,
  4526,
  4870,
  3182,
  3709,
  2762,
  4507,
  4286,
  3300,
  2762,
  2774,
  4935,
  4305,
  2301],
 [4743,
  3274,
  4103,
  4047,
  4712,
  3714,
  5381,
  2834,
  5562,
  4609,
  4610,
  4395,
  4599,
  5658,
  2782,
  4406,
  3184,
  5616,
  4101,
  3497,
  4456,
  4833,
  3755,
  3469,
  5132,
  3964,
  3624,
  5541,
  3678,
  5428,
  5157,
  4333,
  3429,
  5640,
  3219,
  2893,
  3740,
  4695,
  3988,
  5018,
  4274,
  4760,
  4347,
  5257,
  4956,
  3905,
  3397,
  3642,
  3594,
  4862,
  3476,
  5428,
  2739,
  4564,
  3071,
  3951,
  3655,
  4180,
  2943,
  4764,
  3788,
  5638,
  4063,
  3459,
  4705,
  3872,
  4977,
  4672,
  2868,
  5308,
  5222,
  2744,
  3338,
  3401,
  5399,
  5100],
 [1082,
  2068,
  539,
  2103,
  3143,
  1641,
  1837,
  561,
  1090,
  1565,
  2306,
  2600,
  449,
  2838,
  2745,
  2453,
  522,
  3094,
  915,
  1561,
  1505,
  2988,
  3180,
  1854,
  2092,
  1516,
  2073,
  3079,
  910,
  2286,
  1746,
  1139,
  1067,
  1089,
  1309,
  3342,
  1432,
  3266,
  689,
  2376,
  3346,
  1772,
  892,
  1578,
  937,
  975,
  2106,
  2108,
  2996,
  3238,
  2516,
  2469,
  3288,
  3227,
  915,
  712,
  3124,
  1354,
  1682,
  1665,
  1928,
  1424,
  1409,
  2389,
  3215,
  868,
  2289,
  895,
  471,
  617,
  2541,
  1864,
  696,
  1409,
  2175,
  2995],
 [3744,
  2116,
  3528,
  2847,
  1592,
  2639,
  3982,
  3294,
  3559,
  3107,
  3301,
  2189,
  3275,
  2438,
  3444,
  3553,
  4043,
  1643,
  2244,
  2747,
  3183,
  3028,
  3174,
  1927,
  3365,
  3390,
  3568,
  2427,
  4004,
  3665,
  3818,
  4408,
  2304,
  3631,
  1646,
  2796,
  2876,
  3141,
  3993,
  1931,
  3893,
  2706,
  2187,
  2652,
  4240,
  2018,
  2761,
  1515,
  1977,
  1611,
  3820,
  2279,
  2101,
  3651,
  2012,
  3339,
  1672,
  3177,
  2607,
  4108,
  2358,
  2871,
  2637,
  2204,
  1877,
  1475,
  4209,
  1636,
  2565,
  2206,
  3862,
  2497,
  2808,
  2444,
  1903,
  1672],
 [3102,
  4462,
  2030,
  1779,
  2551,
  2079,
  3801,
  4535,
  3539,
  4455,
  4107,
  2183,
  3088,
  2385,
  2226,
  3473,
  2559,
  2293,
  1596,
  3016,
  2131,
  4406,
  2917,
  2230,
  4541,
  4321,
  3265,
  1995,
  2730,
  1906,
  2635,
  3912,
  2098,
  2375,
  2267,
  2346,
  1762,
  2859,
  3121,
  2926,
  1735,
  3614,
  3591,
  3417,
  2620,
  4487,
  2272,
  4454,
  2588,
  1675,
  1914,
  4468,
  2359,
  1918,
  4055,
  3188,
  3851,
  4110,
  3964,
  4390,
  2855,
  4395,
  2900,
  2541,
  3907,
  4547,
  3947,
  4346,
  2503,
  2956,
  1846,
  3520,
  2184,
  2747,
  3873,
  4098],
 [1219,
  3224,
  2126,
  2559,
  542,
  1147,
  1136,
  436,
  2253,
  3131,
  1591,
  1814,
  935,
  2028,
  948,
  2291,
  2516,
  3127,
  2456,
  2998,
  3161,
  2320,
  517,
  2921,
  744,
  2849,
  750,
  616,
  1552,
  1083,
  1720,
  2991,
  1411,
  930,
  1878,
  2833,
  2262,
  2611,
  944,
  1433,
  2281,
  564,
  786,
  2282,
  1417,
  1789,
  2676,
  402,
  2080,
  588,
  1249,
  1378,
  2348,
  1594,
  2208,
  2357,
  503,
  642,
  2914,
  3378,
  3381,
  2615,
  989,
  990,
  616,
  1306,
  1057,
  1994,
  2544,
  1743,
  1185,
  1901,
  1279,
  3177,
  1901,
  2161],
 [1672,
  1574,
  2279,
  1476,
  2112,
  3875,
  2154,
  1466,
  1518,
  3303,
  3717,
  3489,
  1350,
  2358,
  3364,
  1284,
  3464,
  1341,
  1561,
  1343,
  2395,
  1510,
  3919,
  3239,
  1856,
  3638,
  1997,
  3903,
  3023,
  3053,
  2120,
  2890,
  3888,
  1542,
  1967,
  3947,
  3063,
  3914,
  3432,
  3467,
  2747,
  2213,
  3198,
  3900,
  1900,
  2502,
  3043,
  2299,
  1484,
  1712,
  1546,
  2391,
  1241,
  1974,
  1539,
  3560,
  3383,
  2348,
  2872,
  1673,
  3122,
  1496,
  3208,
  3690,
  1247,
  1535,
  2054,
  1326,
  3506,
  3233,
  3495,
  3113,
  2937,
  3115,
  2391,
  3344],
 [1794,
  3031,
  4217,
  3519,
  4466,
  3221,
  4340,
  2815,
  4363,
  2606,
  2014,
  4570,
  4222,
  2499,
  4729,
  2238,
  3126,
  3015,
  2280,
  4566,
  2863,
  3570,
  3359,
  2515,
  3693,
  4502,
  3149,
  2216,
  4405,
  2030,
  2142,
  3887,
  2747,
  3369,
  2326,
  4129,
  2306,
  1753,
  4328,
  2877,
  3476,
  1934,
  2798,
  3853,
  1781,
  2271,
  3501,
  2307,
  3314,
  3140,
  4332,
  3121,
  2213,
  2681,
  2771,
  4494,
  3575,
  2998,
  4702,
  3420,
  2918,
  4662,
  3077,
  3014,
  2972,
  1771,
  4468,
  1914,
  3773,
  2560,
  3690,
  1919,
  3754,
  2976,
  3019,
  2574],
 [3059,
  2777,
  3164,
  3759,
  4260,
  3392,
  2770,
  4780,
  3622,
  3310,
  3607,
  2860,
  2727,
  3893,
  4018,
  2326,
  3168,
  2161,
  4929,
  2592,
  2447,
  3833,
  4954,
  2322,
  4872,
  2658,
  4709,
  2914,
  2886,
  4056,
  2834,
  4059,
  3908,
  4029,
  2323,
  2505,
  2983,
  4687,
  2169,
  3666,
  2406,
  4282,
  4761,
  3070,
  2017,
  2062,
  4075,
  2706,
  2582,
  2608,
  4348,
  4127,
  3834,
  2609,
  4761,
  3783,
  4603,
  4443,
  2781,
  2150,
  3391,
  2031,
  4434,
  3845,
  4762,
  4662,
  3490,
  4067,
  4062,
  4140,
  2361,
  4185,
  2779,
  2682,
  4698,
  4786]]

In [5]:
#reading in distance data
citydata = pd.read_excel(open('P3_DCLocation.xlsx','rb'), sheet_name='citydata')
citydata

           city  demand
0      New York    8622
1   Los Angeles    3999
2       Chicago    2716
3       Houston    3284
4       Phoenix    1626
..          ...     ...
71      Orlando     517
72       Irvine     338
73       Toledo     357
74  Jersey City     569
75  Chula Vista     371

[76 rows x 2 columns]

In [12]:
#converting annual trips to a list:
demand = citydata["demand"].tolist()
demand

[8622,
 3999,
 2716,
 3284,
 1626,
 1580,
 1511,
 1419,
 1341,
 1035,
 950,
 892,
 884,
 879,
 874,
 863,
 859,
 724,
 901,
 693,
 685,
 874,
 683,
 773,
 620,
 414,
 351,
 672,
 440,
 779,
 633,
 416,
 768,
 444,
 791,
 614,
 742,
 793,
 553,
 324,
 463,
 577,
 388,
 575,
 483,
 371,
 425,
 638,
 318,
 580,
 496,
 756,
 357,
 654,
 783,
 755,
 730,
 555,
 524,
 663,
 419,
 537,
 494,
 431,
 371,
 665,
 671,
 795,
 752,
 496,
 646,
 517,
 338,
 357,
 569,
 371]

In [6]:
#converting names of cities to list:
cities = citydata["city"].tolist()
cities

['New York',
 'Los Angeles',
 'Chicago',
 'Houston',
 'Phoenix',
 'Philadelphia',
 'San Antonio',
 'San Diego',
 'Dallas',
 'San Jose',
 'Austin',
 'Jacksonville',
 'San Francisco',
 'Columbus',
 'Fort Worth',
 'Indianapolis',
 'Charlotte',
 'Seattle',
 'Denver',
 'Washington, D.C.',
 'Boston',
 'El Paso',
 'Detroit',
 'Nashville',
 'Memphis',
 'Portland',
 'Oklahoma City',
 'Las Vegas',
 'Louisville',
 'Baltimore',
 'Milwaukee',
 'Albuquerque',
 'Tucson',
 'Fresno',
 'Sacramento',
 'Mesa',
 'Kansas City',
 'Atlanta',
 'Long Beach',
 'Omaha',
 'Raleigh',
 'Colorado Springs',
 'Miami',
 'Virginia Beach',
 'Oakland',
 'Minneapolis',
 'Tulsa',
 'Arlington',
 'New Orleans',
 'Wichita',
 'Cleveland',
 'Tampa',
 'Bakersfield',
 'Aurora',
 'Anaheim',
 'Honolulu',
 'Santa Ana',
 'Riverside',
 'Corpus Christi',
 'Lexington',
 'Stockton',
 'St. Louis',
 'Saint Paul',
 'Henderson',
 'Pittsburgh',
 'Cincinnati',
 'Anchorage',
 'Greensboro',
 'Plano',
 'Newark',
 'Lincoln',
 'Orlando',
 'Irvine',
 'Toledo',
 'Jersey City',
 'Chula Vista']

In [7]:
#converting annual trips to a list:
capacity1 = pd.read_excel(open('P3_DCLocation.xlsx','rb'), sheet_name='DCdata') #Change to your file name and sheet name
capacity1

           location  capacity  fixedcost
0            Durham     20655    3831700
1        Fort Wayne     11279    1848400
2    St. Petersburg     25376    2190000
3            Laredo     40169    1361300
4           Buffalo     25167    1312000
5           Madison     12428    2168300
6           Lubbock     37810    1323800
7          Chandler     23909    1432500
8        Scottsdale      5493    1386600
9              Reno     25840    1577700
10         Glendale     28462    1303100
11          Norfolk     23012    1117800
12    Winstonâ€“Salem     41854    2856900
13  North Las Vegas     14660    1393600
14          Gilbert     49261    1249100
15       Chesapeake     22358    1236600
16           Irving      6008    1275700
17          Hialeah      5526    1840500
18          Garland     30026    1452100
19          Fremont     17341    2114800
20         Richmond     21896    2393800
21            Boise     49754    1266000
22      Baton Rouge     45177    1484700

In [8]:
capacity = capacity1["capacity"].tolist()
capacity

[20655,
 11279,
 25376,
 40169,
 25167,
 12428,
 37810,
 23909,
 5493,
 25840,
 28462,
 23012,
 41854,
 14660,
 49261,
 22358,
 6008,
 5526,
 30026,
 17341,
 21896,
 49754,
 45177]

In [9]:
fixed_costs = capacity1['fixedcost']
fixed_costs

0     3831700
1     1848400
2     2190000
3     1361300
4     1312000
5     2168300
6     1323800
7     1432500
8     1386600
9     1577700
10    1303100
11    1117800
12    2856900
13    1393600
14    1249100
15    1236600
16    1275700
17    1840500
18    1452100
19    2114800
20    2393800
21    1266000
22    1484700
Name: fixedcost, dtype: int64

In [10]:
cities = capacity1['location'].tolist()
cities

['Durham',
 'Fort Wayne',
 'St. Petersburg',
 'Laredo',
 'Buffalo',
 'Madison',
 'Lubbock',
 'Chandler',
 'Scottsdale',
 'Reno',
 'Glendale',
 'Norfolk',
 'Winstonâ€“Salem',
 'North Las Vegas',
 'Gilbert',
 'Chesapeake',
 'Irving',
 'Hialeah',
 'Garland',
 'Fremont',
 'Richmond',
 'Boise',
 'Baton Rouge']

In [13]:
# Declare a concrete model
model = ConcreteModel()
num_dc_loc = 76 #possible SC Location, (columns) index by i
num_city_loc = 23 #possible ciy location, (rows) index them by j
#Declare the decision variables
model.x = Var(range(num_dc_loc), domain = Binary) #Locate SC in that city? Indexed by i
model.y = Var(range(num_city_loc), range(num_dc_loc), domain = NonNegativeReals) # assign a city to a specific SC? Indexed by j,i

#Constraint #1: The amount produced needs to be greater than or equal to demand for each region...
model.Demand = ConstraintList()
for j in range(num_dc_loc):
    model.Demand.add(expr = sum(model.y[i,j] for i in range(num_city_loc)) >= demand[j])

#Constraint #2: The amount produced cannot exceed capacity....
model.Capacity = ConstraintList()
for i in range(num_city_loc):
    model.Capacity.add(expr = sum(model.y[i,j] for j in range(num_dc_loc)) <= model.x[i]*capacity[i])
    
#Set the model Objective...
variable_cost = sum(model.y[i,j]*distances[i][j] for i in range(num_city_loc) for j in range(num_dc_loc))
fixed_cost = sum(model.x[i]*fixed_costs[i] for i in range(num_city_loc))
total_costs = fixed_cost + variable_cost
model.Objective = Objective(expr = total_costs, sense = minimize)

In [14]:
opt = SolverFactory('glpk')
opt.options['mipgap'] = .001
results = opt.solve(model, tee=True)

GLPSOL: GLPK LP/MIP Solver, v4.65
Parameter(s) specified in the command line:
 --mipgap 0.001 --write /var/folders/jk/v8nw40yx6nndkxr3fqdflv5m0000gn/T/tmpolejofr0.glpk.raw
 --wglp /var/folders/jk/v8nw40yx6nndkxr3fqdflv5m0000gn/T/tmp3txqolk4.glpk.glp
 --cpxlp /var/folders/jk/v8nw40yx6nndkxr3fqdflv5m0000gn/T/tmpshderayj.pyomo.lp
Reading problem data from '/var/folders/jk/v8nw40yx6nndkxr3fqdflv5m0000gn/T/tmpshderayj.pyomo.lp'...
/var/folders/jk/v8nw40yx6nndkxr3fqdflv5m0000gn/T/tmpshderayj.pyomo.lp:7371: warning: lower bound of variable 'x1' redefined
/var/folders/jk/v8nw40yx6nndkxr3fqdflv5m0000gn/T/tmpshderayj.pyomo.lp:7371: warning: upper bound of variable 'x1' redefined
100 rows, 1772 columns, 3520 non-zeros
23 integer variables, all of which are binary
7394 lines were read
Writing problem data to '/var/folders/jk/v8nw40yx6nndkxr3fqdflv5m0000gn/T/tmp3txqolk4.glpk.glp'...
9015 lines were written
GLPK Integer Optimizer, v4.65
100 rows, 1772 columns, 3520 non-zeros
23 integer variables, all of which are binary
Preprocessing...
99 rows, 1771 columns, 3519 non-zeros
23 integer variables, all of which are binary
Scaling...
 A: min|aij| =  1.000e+00  max|aij| =  4.975e+04  ratio =  4.975e+04
GM: min|aij| =  1.000e+00  max|aij| =  1.000e+00  ratio =  1.000e+00
EQ: min|aij| =  1.000e+00  max|aij| =  1.000e+00  ratio =  1.000e+00
2N: min|aij| =  6.682e-01  max|aij| =  1.277e+00  ratio =  1.911e+00
Constructing initial basis...
Size of triangular part is 99
Solving LP relaxation...
GLPK Simplex Optimizer, v4.65
99 rows, 1771 columns, 3519 non-zeros
      0: obj =   0.000000000e+00 inf =   6.754e+04 (76)
    100: obj =   1.916300069e+08 inf =   0.000e+00 (0)
*   203: obj =   5.105337727e+07 inf =   0.000e+00 (0)
OPTIMAL LP SOLUTION FOUND
Integer optimization begins...
Long-step dual simplex will be used
+   203: mip =     not found yet >=              -inf        (1; 0)
+   290: >>>>>   6.597110500e+07 >=   5.291047631e+07  19.8% (13; 0)
+   345: >>>>>   6.384635700e+07 >=   5.391041149e+07  15.6% (18; 4)
+   376: >>>>>   5.871100200e+07 >=   5.404213449e+07   8.0% (22; 8)
+   437: >>>>>   5.800649800e+07 >=   5.524383763e+07   4.8% (16; 35)
+   548: mip =   5.800649800e+07 >=   5.798756548e+07 < 0.1% (2; 77)
RELATIVE MIP GAP TOLERANCE REACHED; SEARCH TERMINATED
Time used:   0.1 secs
Memory used: 2.2 Mb (2261591 bytes)
Writing MIP solution to '/var/folders/jk/v8nw40yx6nndkxr3fqdflv5m0000gn/T/tmpolejofr0.glpk.raw'...
1881 lines were written

In [29]:
#printing the solution
print("Obj: Total Distance:", model.Objective())

#printing the SC location
print("City DC Locations and Servicing:")
#for i in range(num_dc_loc):
    #if model.x[i]() == 1:
        #print(cities[i])
for i in range(num_dc_loc):
    if model.x[i]() == 1:
        for j in range(num_city_loc):
                print("DC:", cities[i],"services", cities[j])

Obj: Total Distance: 58006498.0
City DC Locations and Servicing:
DC: Lubbock services Durham
DC: Lubbock services Fort Wayne
DC: Lubbock services St. Petersburg
DC: Lubbock services Laredo
DC: Lubbock services Buffalo
DC: Lubbock services Madison
DC: Lubbock services Lubbock
DC: Lubbock services Chandler
DC: Lubbock services Scottsdale
DC: Lubbock services Reno
DC: Lubbock services Glendale
DC: Lubbock services Norfolk
DC: Lubbock services Winstonâ€“Salem
DC: Lubbock services North Las Vegas
DC: Lubbock services Gilbert
DC: Lubbock services Chesapeake
DC: Lubbock services Irving
DC: Lubbock services Hialeah
DC: Lubbock services Garland
DC: Lubbock services Fremont
DC: Lubbock services Richmond
DC: Lubbock services Boise
DC: Lubbock services Baton Rouge
DC: Glendale services Durham
DC: Glendale services Fort Wayne
DC: Glendale services St. Petersburg
DC: Glendale services Laredo
DC: Glendale services Buffalo
DC: Glendale services Madison
DC: Glendale services Lubbock
DC: Glendale services Chandler
DC: Glendale services Scottsdale
DC: Glendale services Reno
DC: Glendale services Glendale
DC: Glendale services Norfolk
DC: Glendale services Winstonâ€“Salem
DC: Glendale services North Las Vegas
DC: Glendale services Gilbert
DC: Glendale services Chesapeake
DC: Glendale services Irving
DC: Glendale services Hialeah
DC: Glendale services Garland
DC: Glendale services Fremont
DC: Glendale services Richmond
DC: Glendale services Boise
DC: Glendale services Baton Rouge
DC: Winstonâ€“Salem services Durham
DC: Winstonâ€“Salem services Fort Wayne
DC: Winstonâ€“Salem services St. Petersburg
DC: Winstonâ€“Salem services Laredo
DC: Winstonâ€“Salem services Buffalo
DC: Winstonâ€“Salem services Madison
DC: Winstonâ€“Salem services Lubbock
DC: Winstonâ€“Salem services Chandler
DC: Winstonâ€“Salem services Scottsdale
DC: Winstonâ€“Salem services Reno
DC: Winstonâ€“Salem services Glendale
DC: Winstonâ€“Salem services Norfolk
DC: Winstonâ€“Salem services Winstonâ€“Salem
DC: Winstonâ€“Salem services North Las Vegas
DC: Winstonâ€“Salem services Gilbert
DC: Winstonâ€“Salem services Chesapeake
DC: Winstonâ€“Salem services Irving
DC: Winstonâ€“Salem services Hialeah
DC: Winstonâ€“Salem services Garland
DC: Winstonâ€“Salem services Fremont
DC: Winstonâ€“Salem services Richmond
DC: Winstonâ€“Salem services Boise
DC: Winstonâ€“Salem services Baton Rouge
DC: Irving services Durham
DC: Irving services Fort Wayne
DC: Irving services St. Petersburg
DC: Irving services Laredo
DC: Irving services Buffalo
DC: Irving services Madison
DC: Irving services Lubbock
DC: Irving services Chandler
DC: Irving services Scottsdale
DC: Irving services Reno
DC: Irving services Glendale
DC: Irving services Norfolk
DC: Irving services Winstonâ€“Salem
DC: Irving services North Las Vegas
DC: Irving services Gilbert
DC: Irving services Chesapeake
DC: Irving services Irving
DC: Irving services Hialeah
DC: Irving services Garland
DC: Irving services Fremont
DC: Irving services Richmond
DC: Irving services Boise
DC: Irving services Baton Rouge
DC: Fremont services Durham
DC: Fremont services Fort Wayne
DC: Fremont services St. Petersburg
DC: Fremont services Laredo
DC: Fremont services Buffalo
DC: Fremont services Madison
DC: Fremont services Lubbock
DC: Fremont services Chandler
DC: Fremont services Scottsdale
DC: Fremont services Reno
DC: Fremont services Glendale
DC: Fremont services Norfolk
DC: Fremont services Winstonâ€“Salem
DC: Fremont services North Las Vegas
DC: Fremont services Gilbert
DC: Fremont services Chesapeake
DC: Fremont services Irving
DC: Fremont services Hialeah
DC: Fremont services Garland
DC: Fremont services Fremont
DC: Fremont services Richmond
DC: Fremont services Boise
DC: Fremont services Baton Rouge